# Este archivo existe únicamente para compilar el backend de Zuros
name = "zuros-store-backend"
main = "src/index.ts"
compatibility_date = "2025-03-20"
keep_vars = true
[observability.logs]
enabled = true